# Generated by Django 3.0.5 on 2020-04-10 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=250)),
                ('entrance_fee', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=200)),
                ('open', models.BooleanField()),
                ('image', models.CharField(max_length=250)),
                ('avg_rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('L', 'Loding'), ('A', 'Activities'), ('F', 'Food')], default='Activities', max_length=1)),
                ('comments', models.TextField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('park_rating', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Park')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
