# Generated by Django 3.0.5 on 2020-04-14 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200413_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='open',
        ),
    ]
